### ISSUE TITLE
MonitRC error

### ISSUE THREAD

**Issue by bimlyas** [digitalmine/Guide#2]
I got this when line $ sudo monit reload

/etc/monit/monitrc:289: Include failed -- Success '/etc/monit/conf.d/*'
/etc/monit/monitrc:290: Include failed -- Success '/etc/monit/conf-enabled/*'
Reinitializing monit daemon

After that i try to check getinfo and the blocks is stuck at 0

Please Help

**Comment by digitalmine** [comment]
Not maintained any more.
